name: Lint and isort

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: psf/black@22.3.0
        with:
          options: "--check --verbose"
          src: "./src"
      - uses: jamescurtin/isort-action@master
        with:
          sortPaths: "./src/"
          requirementsFiles: "./src/requirements.txt"